// test/auth_test.rest (REST API Test)
### Register User
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "username": "gajah_13h6",
    "email": "gajah2@gmail.com",
    "password": "Gajah123",
    "confirmPassword": "Gajah123"
}

### Login User
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "identifier": "Hello123",
    "password": "Hello123"
}

### refresh token
POST http://localhost:8000/api/auth/refresh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiZ2FqYWhfMTNoNiIsImVtYWlsIjoiZ2FqYWgyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzMzIxNTMyLCJleHAiOjE3NDM5MjYzMzJ9.DyNxzHzWG30-nf5fByTPOihJo3t5GN4VcO7RzkoEmFo


### Test Trending Films and Series
GET http://localhost:8000/api/films/trending


